id: PC922EF6A
initial_creation_type: input
source_metadata:
  Title: Abhisamayālaṇkāraloka
  Editor: Giuseppe Tucci
  Publisher: Oriental Institute
  Place of Publication: Baroda
  Year: '1932'
  Prathamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Dvitīyaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Tṛtīyaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Caturthaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Pañcamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ṣaṣṭhaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Saptamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Aṣṭamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Navamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Daśamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ekādaśaparivarttaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Dvādaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Trayodaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Caturdaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Pañcadaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ṣoḍaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Saptadaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Aṣṭādaśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ūnaviṃśaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Viṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ekaviṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Trayoviṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Pañcaviṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ṣaḍviṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Saptaviṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Aṣṭāviṃśatitamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ūnatriṃśattamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Triṃśattamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Ekatriṃśattamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
  Dvātriṃśattamaparivartaḥ:
    Text Version: ''
    Input Personnel: ''
    Input Date: ''
    Proof Reader: ''
    Supplier: ''
    Sponsor: ''
created_at: '2022-03-08T16:45:33.161591'
last_modified_at: '2022-03-08T16:45:33.161603'
